---
# This task installs and enables apache on webservers
- name: ensure apache is installed
  yum: name=httpd state=latest
- name: ensure apache is running
  service: name=httpd state=started enabled=yes
- name: copy files to document root
  copy: src=logo.jpg dest=/var/www/html/logo.jpg
- name: copy application code to document root
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart apache

